# Dockerfile.streamlit
FROM python:3.11-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app

# Installer les dépendances système
RUN apt-get update -o Acquire::Retries=3 && apt-get install -y --no-install-recommends \
    libpq-dev \
    libexpat1 \
    mdbtools \
    && rm -rf /var/lib/apt/lists/*

# Installer les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY src/ ./src/
COPY config/ ./config/

# Créer les dossiers
RUN mkdir -p data output

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "src/app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]